version: "3.7"

services:
  nginx:
    image: sg-nginx-image:1.0
    build:
      context: ..
      dockerfile: devops/Dockerfile-nginx
    container_name: sg-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../server/static:/home/app/microservice/static
    depends_on:
      - server
    restart: on-failure
    networks:
      network:
        aliases:
          - nginx
  server:
    restart: always
    stdin_open: true
    image: sg-server-image:1.0
    build:
      context: ..
      dockerfile: devops/Dockerfile-server
    container_name: sg-server
    command: python3 /app/manage.py runserver 0.0.0.0:8000
    # command: daphne sexybaby.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - ../server:/app
    environment:
      - DEPLOY_ENV=${DEPLOY_ENV:-local}
    env_file:
      - commons.env
      - secrets.env
    logging:
      options:
        max-size: 10m
    expose:
      - 8000
    networks:
      network:
        aliases:
          - server

networks:
  network:
    name: sexy-girls-network
